const videoLinks = {
        "explore | Africam Tau": "https://www.youtube.com/embed/DsNtwGJXTTs",
        "explore | Tembe Elephant": "https://www.youtube.com/embed/VUJbDTIYlM4",
        "explore | Rosies Pan": "https://www.youtube.com/embed/ItdXaWUVF48",
        "explore | African Water Hole": "https://www.youtube.com/embed/KyQAB-TKOVA",
        "explore | Olifants River": "https://www.youtube.com/embed/_NXaovxB-Bk",
        "explore | African River": "https://www.youtube.com/embed/2swy9gysvOY",
        "explore | African Animals": "https://www.youtube.com/embed/O8xVFhgEv6Q",
        "explore | African Safari": "https://www.youtube.com/embed/QkWGGhtTA4k",
        "explore | Stony Point Penguin": "https://www.youtube.com/embed/StGk_2DA5ig",
        "explore | Outdoor Rhino Cam": "https://www.youtube.com/embed/oruIH1ZadqE",
        "explore | Indoor Rhino Cam": "https://www.youtube.com/embed/0fxKkyTah5o",
        "explore | Nkorho Bush Lodge": "https://www.youtube.com/embed/dIChLG4_WNs",
        "Namibia | Namib Desert": "https://www.youtube.com/embed/ydYDqZQpim8",
        "Namibia | Kalahari Desert": "https://www.youtube.com/embed/fPd7Ys7FC0I",
        "Namibia | Okaukuejo waterhole in Etosha": "https://www.youtube.com/embed/DAmFZj1y_a0",
        "Africam | Naledi Dam": "https://www.youtube.com/embed/S4GIPXZnQTM",
        "Africam | Kruger Shalati – Skukuza": "https://www.youtube.com/embed/zh8O_O6aX0Q",
        "Africam | Kruger Shalati – Shalati Sunrise": "https://www.youtube.com/embed/ddZoJge-fKM",
        "Africam | Simbavati Waterside | Wildlife Live Stream": "https://www.youtube.com/embed/xgOwXsa1Z2Q",
        "Africam | Rhinos Live | Hoedspruit Endangered Species Centre": "https://www.youtube.com/embed/rnF5SaP6kxk",
        "Africam | Victoria Falls Safari Lodge - Waterhole": "https://www.youtube.com/embed/I113nq5PmK4",
        "Africam | Mabula Game Lodge": "https://www.youtube.com/embed/iFwbWzCH86o",
        "Africam | Victoria Falls Safari Lodge - Sky Cam": "https://www.youtube.com/embed/3fQtAd5pl08",
        "Africam | Tembo Plains ZW": "https://www.youtube.com/embed/jH3e5w4BWGA",
        "explore | Wolong Grove Panda Yard": "https://www.youtube.com/embed/3szkFHfr6sA",
        "explore | Gengda Valley Panda Yard": "https://www.youtube.com/embed/DP9hbJmwbNU",
        "explore | Happiness Village Baby Panda Garden": "https://www.youtube.com/embed/58aHnTp0-JY",
        "explore | Happiness Village Baby Panda Park": "https://www.youtube.com/embed/tCcd6ZkExuo",
        "explore | Polar Bears Cape South - Wapusk National Park": "https://www.youtube.com/embed/lyX7ZxWU64A",
        "explore | Polar Bears Cape East - Wapusk National Park": "https://www.youtube.com/embed/gdCQkNqYIVc",
        "explore | The Mixed Species Flying Fox Cam": "https://www.youtube.com/embed/zH0IM95ia5w",
        "explore | The Giant Flying Fox": "https://www.youtube.com/embed/ojBaem3bwsE",
        "explore | Red Panda Forest Park": "https://www.youtube.com/embed/Ihr_nwydXi0",
        "explore | International Wolf Center North": "https://www.youtube.com/embed/5e4lsEe4Vew",
        "explore | International Wolf Center South": "https://www.youtube.com/embed/DRxYSIoBusQ",
        "explore | Underwater Manatee Cam": "https://www.youtube.com/embed/yPSYdCWRWFA",
        "explore | Tropical Reef Camera": "https://www.youtube.com/embed/DHUnz4dyb54"
    };